#!/usr/bin/env node
const { spawn } = require('child_process');

const pkg = process.argv[2];
if (!pkg) {
  console.error('No package specified');
  process.exit(1);
}

async function run(command, args) {
  console.log(`${command} ${args.join(' ')}`);
  const child = spawn(command, args);

  child.stdout.pipe(process.stdout);
  child.stderr.pipe(process.stderr);
  return new Promise((resolve, reject) => {
    child.on('exit', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error());
      }
    })
  });
}

async function main() {
  await run('pnpm', ['install', '--frozen-lockfile', '--prefer-offline', '--filter', `@kenchi/${pkg}...`]);
}
main();
